[project]
name = "synclair"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "fastexcel>=0.21.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.52.4",
    "xlsx2csv>=0.8.6",
    "xlsxwriter>=3.2.9",
]

[dependency-groups]

dev = [
    "pytest",
    "ruff",
    "mypy",
    "pre-commit",
    "httpx>=0.28.1",
]

[tool.uv.workspace]
members = ["packages/*"]
